custom_modal.settings:
  type: config_object
  label: Modal content type settings
  mapping:
    allowed_types:
      type: sequence
      label: Content types the modal can display on
      sequence:
        type: string
        label: Content type
