<?php

/**
 * @file
 * RSVP list module hooks.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function rsvplist_form_node_form_alter(&$form, FormStateInterface $form_state) {
  $node = $form_state->getFormObject()->getEntity();
  $current_node_type = $node->getType();
  $rsvp_config = \Drupal::config('rsvplist.settings');
  $allowed_types = $rsvp_config->get('allowed_types');

  if (in_array($current_node_type, $allowed_types)) {
    $form['rsvplist'] = [
      '#type' => 'details',
      '#title' => t('RSVP Collection'),
      '#access' => \Drupal::currentUser()->hasPermission('administer rsvplist'),
      '#group' => 'advanced',
      '#weight' => 50,
    ];

    $enabler = \Drupal::service('rsvplist.enabler');
    $enabled = $enabler->isEnabled($node);

    $form['rsvplist']['rsvplist_enabled'] = [
      '#type' => 'checkbox',
      '#title' => t('Collect RSVP email addresses for this node.'),
      '#default_value' => $enabled,
    ];
  }

  foreach ($form['actions'] as $action => $_) {
    if ($action !== 'preview' && isset($form['actions'][$action]['#type'])
      && $form['actions'][$action]['#type'] === 'submit') {
      $form['actions'][$action]['#submit'][] = 'rsvplist_form_node_form_submit';
    }
  }
}

/**
 * Form submission handler for RSVP item field on the node form.
 */
function rsvplist_form_node_form_submit(&$form, FormStateInterface $form_state) {
  $enabler = \Drupal::service('rsvplist.enabler');
  $node = $form_state->getFormObject()->getEntity();
  if ($form_state->getValue('rsvplist_enabled')) {
    $enabler->setEnabled($node);
  } else {
    $enabler->deleteEnabled($node);
  }
}

/**
 * Implements hook_theme().
 */
function rsvplist_theme($existing, $type, $theme, $path) {
  return [
    'rsvplist_report' => [
      'variables' => ['message' => NULL, 'table_rows' => [], 'empty_message' => NULL],
    ],
  ];
}
